#!/bin/sh

cd ./dynamicMesh2D/dynamicMesh
wmake
cd ../dynamicFvMesh
wmake

cd ../..
cd ./DLBFoam-1.0-1.0_OF8/src/thermophysicalModels/chemistryModel
wmake

cd ../../../..
cd ./fluxSchemes_improved
wmake

cd ..
wmake
#------------------------------------------------------------------------------
